# Importación de datos

In [37]:
import pandas as pd

def cargarDatos() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Carga los datasets de las tiendas desde archivos locales o URLs de respaldo.

    Return:
    - Tupla con cuatro DataFrames en el orden: tienda1, tienda2, tienda3, tienda4.
    """
    try:
        # Intenta cargar localmente primero.
        print("Función iniciada.")
        print("Cargando archivos localmente.")
        folder_name = "base-de-datos-challenge1-latam/"
        tienda_1 = pd.read_csv(folder_name + "tienda_1.csv")
        tienda_2 = pd.read_csv(folder_name + "tienda_2.csv")
        tienda_3 = pd.read_csv(folder_name + "tienda_3.csv")
        tienda_4 = pd.read_csv(folder_name + "tienda_4.csv")

    except FileNotFoundError:
        # Fallback a URLs (para Colab o si faltan archivos locales).
        print("No fue posible cargar uno o varios archivos locales.")
        print("Cargando archivos remotamente.")
        try: 
            base_url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/"
            tienda_1 = pd.read_csv(base_url + "tienda_1%20.csv")
            tienda_2 = pd.read_csv(base_url + "tienda_2.csv")
            tienda_3 = pd.read_csv(base_url + "tienda_3.csv")
            tienda_4 = pd.read_csv(base_url + "tienda_4.csv")
            print("Archivos cargados remotamente.")
            return tienda_1, tienda_2, tienda_3, tienda_4
        except Exception as e:
            print("No fue posible cargar los datos. Verifique la excepción.")
            print(f'Excepción: {e}')
            
    except Exception as e:
        print("No fue posible cargar los datos. Verifique la excepción.")
        print(f'Excepción: {e}')

    else:
        print("Archivos cargados localmente.")    
        return tienda_1, tienda_2, tienda_3, tienda_4
    
    finally:
        print("Función terminada")

In [38]:
tienda1, tienda2, tienda3, tienda4 = cargarDatos()
tienda1.head()

Función iniciada.
Cargando archivos localmente.
Archivos cargados localmente.
Función terminada

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

## Conozca el conjunto de datos

El objetivo es comparar las 4 tiendas, así que debemos asegurarnos que los DataFrames (DFs) contienen el mismo número de columnas, en el mismo orden y con el mismo tipo de datos.
Como referencia inicial usaremos la Tienda 1.

In [39]:
tienda1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2359 entries, 0 to 2358
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Producto                2359 non-null   object
 1   Categoría del Producto  2359 non-null   object
 2   Precio                  2359 non-null   float64
 3   Costo de envío          2359 non-null   float64
 4   Fecha de Compra         2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Lugar de Compra         2359 non-null   object
 7   Calificación            2359 non-null   int64
 8   Método de pago          2359 non-null   object
 9   Cantidad de cuotas      2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.3+ KB

Ahora sabemos que en teoría cada DF debe tener 12 columnas:
- 4 de tipo float
- 2 de tipo int64
- 6 de tipo obj

Comprobamos que el index (nombre de columna) y orden de las columnas sea el mismo para los 4 DFs mediante el método equals():

In [40]:
tienda1.columns

Index(['Producto', 'Categoría del Producto', 'Precio', 'Costo de envío',
       'Fecha de Compra', 'Vendedor', 'Lugar de Compra', 'Calificación',
       'Método de pago', 'Cantidad de cuotas', 'lat', 'lon'],
      dtype='object')

In [41]:
type(tienda1.columns)

pandas.core.indexes.base.Index

In [42]:
tienda1.columns.equals(tienda2.columns) and \
tienda1.columns.equals(tienda3.columns) and \
tienda1.columns.equals(tienda4.columns)

True

Comprobamos que el tipo de dato de las columnas sea el mismo para los 4 DFs:

In [43]:
tienda1.dtypes

Producto                   object
Categoría del Producto     object
Precio                    float64
Costo de envío            float64
Fecha de Compra            object
Vendedor                   object
Lugar de Compra            object
Calificación                int64
Método de pago             object
Cantidad de cuotas          int64
lat                       float64
lon                       float64
dtype: object

In [44]:
type(tienda1.dtypes)

pandas.core.series.Series

In [45]:
tienda1.dtypes.equals(tienda2.dtypes) \
and tienda1.dtypes.equals(tienda3.dtypes) \
and tienda1.dtypes.equals(tienda4.dtypes)

True

En conclusión, los 4 DFs cuentan con la misma estructura, es decir, mismas columnas, mismo order y mismo tipo de datos.

# Concatenación de DataFrames

Para hacer el análisis más práctico y ahorrarnos una líneas de código, vamos a crear un DF que contenga los datos de todas las tiendas.

Para distinguir un DF de otro, y poder agruparlos en el futuro, vamos a crear una columna que indique a que tienda pertenece y después vamos a concatenar todos los DFs en uno sólo.

In [46]:
tienda1["Tienda"] = 1
tienda2["Tienda"] = 2
tienda3["Tienda"] = 3
tienda4["Tienda"] = 4

In [47]:
tiendas = pd.concat([tienda1, tienda2, tienda3, tienda4])
tiendas

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon,Tienda
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175,1
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359,1
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444,1
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250,1
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2353,Mesa de comedor,Muebles,227700.0,12600.0,12/02/2020,Camila Rivera,Medellín,5,Tarjeta de crédito,1,6.25184,-75.56359,4
2354,Silla de oficina,Muebles,342000.0,18600.0,17/05/2022,Felipe Santos,Bucaramanga,5,Tarjeta de crédito,3,7.12539,-73.11980,4
2355,Vaso térmico,Deportes y diversión,36700.0,2400.0,03/05/2022,Camila Rivera,Bogotá,5,Tarjeta de crédito,1,4.60971,-74.08175,4
2356,Set de ollas,Artículos para el hogar,151800.0,8300.0,15/06/2020,Blanca Ramirez,Cali,5,Tarjeta de crédito,1,3.43722,-76.52250,4
2357,Cuerda para saltar,Deportes y diversión,11200.0,1300.0,17/11/2021,Felipe Santos,Bogotá,5,Tarjeta de crédito,1,4.60971,-74.08175,4

Como curiosidad, es posible crear un índice personalizado.

In [48]:
# tienda5 = tienda1.copy()
# tienda5["Tienda"] = 5
# tienda5.index = [f'1-{i}' for i in range(len(tienda5))]
# tienda5

# Tratamiento de valores nulos

Es importante comprobar si nuestro DF consolidado tiene valores nulos, en dado caso, se eliminarán dichos registros.

Notar el mensaje de error.

In [49]:
tiendas.groupby("Tienda").isnull().sum()

AttributeError: 'DataFrameGroupBy' object has no attribute 'isnull'

La mejor opción es aplicar apply() para lograr agrupar todos los datos en base al número de "Tienda", y a su vez, dentro de cada tienda agrupar el conteo de los valores nulos por columna.

In [50]:
tiendas.groupby("Tienda").apply(lambda x: x.isnull().sum(), include_groups=False)

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
Tienda,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0

En conclusión, no hay valores nulos, no es necesario ninguna modificación

# Tratamiento de valores inconsistentes

# Análisis de datos

## 1. Análisis de facturación

## 2. Ventas por categoría

## 3. Calificación promedio de la tienda

## 4. Productos más y menos vendidos

## 5. Envío promedio por tienda